module.exports = [
    {
        "owner": 1,
        // "owner": "jim@jim.com",
        "title": "Hayden",
        'food': 'Good',
        'beer': 'Amazing',
        'cocktails': 'Bad',
        'wine': 'Decent',
        'from': '3',
        'to': '7',
        'fromTimeOfDay': 'am',
        'toTimeOfDay': 'pm',
        "description": "Oysters and Seafood"
    },
    {
        "owner": 1,
        // "owner": "jim@jim.com",
        "title": "Burger Place",
        'food': 'Good',
        'beer': 'Amazing',
        'cocktails': 'Bad',
        'wine': 'Decent',
        'from': '4',
        'to': '9',
        'fromTimeOfDay': 'am',
        'toTimeOfDay': 'pm',
        "description": "Good burgers"
    },
    {
        "owner": 1,
        // "owner": "jim@jim.com",
        "title": "Simpang",
        'food': 'Good',
        'beer': 'Amazing',
        'cocktails': 'Bad',
        'wine': 'Decent',
        'from': '5',
        'to': '8',
        'fromTimeOfDay': 'am',
        'toTimeOfDay': 'pm',
        "description": "Really good indonesian food"
    },
    {
        "owner": 3,
        // ""owner"": "Bob@Bob.com",
        "title": "Shwarmaland",
        'food': 'Good',
        'beer': 'Amazing',
        'cocktails': 'Bad',
        'wine': 'Decent',
        'from': '5',
        'to': '7',
        'fromTimeOfDay': 'am',
        'toTimeOfDay': 'pm',
        "description": "Good wraps and plates"
    },
    {
        "owner": 4,
        // "owner": "Bob@Bob.com",
        "title": "Bigfoot",
        'food': 'Good',
        'beer': 'Amazing',
        'cocktails': 'Bad',
        'wine': 'Decent',
        'from': '5',
        'to': '7',
        'fromTimeOfDay': 'am',
        'toTimeOfDay': 'pm',
        "description": "Good happy hour spot with taco stand"
    },
    {
        "owner": 4,
        // "owner": "Scott@hayden.Scott",
        "title": "Night + Market Song",
        'food': 'Good',
        'beer': 'Amazing',
        'cocktails': 'Bad',
        'wine': 'Decent',
        'from': '5',
        'to': '7',
        'fromTimeOfDay': 'am',
        'toTimeOfDay': 'pm',
        "description": "Best thai food in L.A"
    },
]